"""FastAPI 请求与响应模型。"""

from .api import (
    AIConfigUpdate,
    AIModelUpdate,
    ChatRequest,
    ChatResponse,
    CompanionContextV1,
    CompanionMigrationState,
    ConsolidateContextRequest,
    ConsolidateContextResponse,
    DiagnosticEvent,
    ExperienceMilestone,
    Message,
    RelationshipDimensions,
    RelationshipState,
    RoleArchiveRequest,
    StateMutationRequest,
    StateReplaceRequest,
    SummarizeRequest,
    SummarizeResponse,
    TTSRequest,
)

__all__ = [
    "AIConfigUpdate",
    "AIModelUpdate",
    "ChatRequest",
    "ChatResponse",
    "CompanionContextV1",
    "CompanionMigrationState",
    "ConsolidateContextRequest",
    "ConsolidateContextResponse",
    "DiagnosticEvent",
    "ExperienceMilestone",
    "Message",
    "RelationshipDimensions",
    "RelationshipState",
    "RoleArchiveRequest",
    "StateMutationRequest",
    "StateReplaceRequest",
    "SummarizeRequest",
    "SummarizeResponse",
    "TTSRequest",
]
